language: node_js
node_js:
- '12'
services:
- docker
notifications:
  email: false
  slack:
    rooms:
      secure: ch7kItVmQNgOPGgJpJrQvkZ/tgvkMYA6+HNPRpK63uQef8PQunbXIQGHknL2eaQ2n+LLmpPgrwNa9VjK4GzhHDWcaUqD4eRhnSYCmzCnNDXlZguf3AU4yge1d6EviBF0x5OOOF1UrC6g8sUjvKtllnKRromFUQ1sNAu7feWKtnXXAaE/y5S5JDTk+bg/ejM0XHuqMZpeOMfgrsc9e9jeZ8gSRP/1guE00NpvPAxkhvwRcuftFPagnuj6w/bb2fXN8dKrVspmWQX7Efeb4dcUoAVTh3LhERzgQ7T4HqVv2xD4y4uN6CKRRuu8O9NKnbuMuNuBuiumq6d4uaZz4igwwcYxrjcEFrbHfwITpfuVEvNGFK2ZiyqDMBVG/6NlTxO/+SUn8PsfjxIHuldg1K9i/jT6zVUuyC+bSu+JzdeDmFmWTnXLawXIVe+7CgWsEmpClHrDp5/B8nEbumy8npnzmvQXMjLrUXWWFzOBAmyAsBlBJVPz/yx4Z+1ctiyZ3+Qx+YfFvyW0FAeRDfmGReQjbeZnP2QOXyc2KMMCsU3JZhq49eB9FnIF3Qu1MFsybkgPJ2AJUe9cQ/Us37nnNM1joPcNOmi3VOFFb5MPgtUe1CpJPfbHUyzGhK65KIoOlDGIqR688kZVagsxpfhoVe7sZhwCapvRbgOrbERYCIW2gBU=
    on_success: always
    on_failure: always
script:
- |
  IMAGE_NAME="$TRAVIS_REPO_SLUG"
  if [[ -z "$TRAVIS_TAG" ]]; then
    IMAGE_TAG=latest
  else
    IMAGE_TAG=$(node -p -e "require('./package.json').version")
  fi
  docker build -f dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
before_deploy:
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
deploy:
  provider: script
  script: docker push $IMAGE_NAME:$IMAGE_TAG
  on:
    all_branches: true
